### PR TITLE
Updates navigation links

### PR DESCRIPTION
**Pull request by devinepk**
- Fixed navigation from personal page to Home
- Fixed navigation from personal page to Students

Please review.

### CODE REVIEW

**Comment by JTHall94** [comment]
Looks good, you could style it after our example "Bob" page for extra uniformity (and that sweet arrow). +1

**Comment by kendrajordan** [comment]
+1

**Comment by bmizepatterson** [comment]
Don't forget to merge into dev instead of master or face Janine's wrath :)

**Comment by Cgmccarty** [comment]
+1, @devinepk make sure you check @bmizepatterson comment!

**Pull request merged**
